package coolapk

type FeedData struct {
	Data struct {
		Id                int           `json:"id"`
		Type              int           `json:"type"`
		Fid               int           `json:"fid"`
		Forwardid         string        `json:"forwardid"`
		SourceId          string        `json:"source_id"`
		Uid               int           `json:"uid"`
		Username          string        `json:"username"`
		DyhId             int           `json:"dyh_id"`
		DyhName           string        `json:"dyh_name"`
		Ttype             int           `json:"ttype"`
		Tcat              int           `json:"tcat"`
		Tid               int           `json:"tid"`
		Ttitle            string        `json:"ttitle"`
		Tpic              string        `json:"tpic"`
		Turl              string        `json:"turl"`
		Tinfo             string        `json:"tinfo"`
		MessageTitle      string        `json:"message_title"`
		MessageTitleMd5   string        `json:"message_title_md5"`
		MessageKeywords   string        `json:"message_keywords"`
		MessageCover      string        `json:"message_cover"`
		Message           string        `json:"message"`
		Pic               string        `json:"pic"`
		MessageLength     int           `json:"message_length"`
		Issummary         int           `json:"issummary"`
		Istag             int           `json:"istag"`
		IsHtmlArticle     int           `json:"is_html_article"`
		Tags              string        `json:"tags"`
		Label             string        `json:"label"`
		UserTags          string        `json:"user_tags"`
		MediaType         int           `json:"media_type"`
		MediaPic          string        `json:"media_pic"`
		MediaUrl          string        `json:"media_url"`
		ExtraType         int           `json:"extra_type"`
		ExtraKey          string        `json:"extra_key"`
		ExtraTitle        string        `json:"extra_title"`
		ExtraUrl          string        `json:"extra_url"`
		ExtraPic          string        `json:"extra_pic"`
		ExtraInfo         string        `json:"extra_info"`
		ExtraStatus       int           `json:"extra_status"`
		Location          string        `json:"location"`
		Fromid            int           `json:"fromid"`
		Fromname          string        `json:"fromname"`
		Likenum           int           `json:"likenum"`
		Burynum           int           `json:"burynum"`
		Commentnum        int           `json:"commentnum"`
		Replynum          int           `json:"replynum"`
		Forwardnum        int           `json:"forwardnum"`
		Reportnum         int           `json:"reportnum"`
		Relatednum        int           `json:"relatednum"`
		Favnum            int           `json:"favnum"`
		ShareNum          int           `json:"share_num"`
		CommentBlockNum   int           `json:"comment_block_num"`
		QuestionAnswerNum int           `json:"question_answer_num"`
		QuestionFollowNum int           `json:"question_follow_num"`
		Hitnum            int           `json:"hitnum"`
		Viewnum           int           `json:"viewnum"`
		FeedScore         int           `json:"feed_score"`
		RankScore         int           `json:"rank_score"`
		VoteScore         int           `json:"vote_score"`
		AtCount           int           `json:"at_count"`
		UrlCount          int           `json:"url_count"`
		TagCount          int           `json:"tag_count"`
		ChangeCount       int           `json:"change_count"`
		Recommend         int           `json:"recommend"`
		IsAnonymous       int           `json:"is_anonymous"`
		IsHidden          int           `json:"is_hidden"`
		IsHeadline        int           `json:"is_headline"`
		DisallowReply     int           `json:"disallow_reply"`
		Status            int           `json:"status"`
		MessageStatus     int           `json:"message_status"`
		BlockStatus       int           `json:"block_status"`
		Dateline          int           `json:"dateline"`
		Lastupdate        int           `json:"lastupdate"`
		LastChangeTime    int           `json:"last_change_time"`
		DeviceTitle       string        `json:"device_title"`
		DeviceName        string        `json:"device_name"`
		DeviceRom         string        `json:"device_rom"`
		DeviceBuild       string        `json:"device_build"`
		RecentReplyIds    string        `json:"recent_reply_ids"`
		RecentHotReplyIds string        `json:"recent_hot_reply_ids"`
		RecentLikeList    string        `json:"recent_like_list"`
		RelatedDyhIds     string        `json:"related_dyh_ids"`
		PostSignature     string        `json:"post_signature"`
		MessageSignature  string        `json:"message_signature"`
		FetchType         string        `json:"fetchType"`
		EntityId          int           `json:"entityId"`
		AvatarFetchType   string        `json:"avatarFetchType"`
		UserAvatar        string        `json:"userAvatar"`
		EntityTemplate    string        `json:"entityTemplate"`
		EntityType        string        `json:"entityType"`
		Url               string        `json:"url"`
		FeedType          string        `json:"feedType"`
		FeedTypeName      string        `json:"feedTypeName"`
		TurlTarget        string        `json:"turlTarget"`
		IsModified        int           `json:"isModified"`
		EnableModify      int           `json:"enableModify"`
		Info              string        `json:"info"`
		InfoHtml          string        `json:"infoHtml"`
		PicArr            []string      `json:"picArr"`
		DeviceTitleUrl    string        `json:"device_title_url"`
		Relateddata       []interface{} `json:"relateddata"`
		MediaInfo         string        `json:"media_info"`
		SourceFeed        interface{}   `json:"sourceFeed"`
		ForwardSourceType string        `json:"forwardSourceType"`
		ShareUrl          string        `json:"shareUrl"`
		Title             string        `json:"title"`
		ExtraFromApi      string        `json:"extra_fromApi"`
		CanDisallowReply  int           `json:"canDisallowReply"`
		DisallowRepost    int           `json:"disallow_repost"`
		LongLocation      string        `json:"long_location"`
		IsWhiteFeed       int           `json:"is_white_feed"`
		EditorTitle       string        `json:"editor_title"`
		TopReplyIds       []string      `json:"top_reply_ids"`
		MessageBrief      string        `json:"message_brief"`
		MessageRawOutput  string        `json:"message_raw_output"`
		ReplyRows         []interface{} `json:"replyRows"`
		ReplyRowsCount    int           `json:"replyRowsCount"`
		ReplyRowsMore     int           `json:"replyRowsMore"`
		UserInfo          struct {
			Uid                 int    `json:"uid"`
			Username            string `json:"username"`
			Admintype           int    `json:"admintype"`
			Groupid             int    `json:"groupid"`
			Usergroupid         int    `json:"usergroupid"`
			Level               int    `json:"level"`
			Experience          int    `json:"experience"`
			Status              int    `json:"status"`
			BlockStatus         int    `json:"block_status"`
			Usernamestatus      int    `json:"usernamestatus"`
			Avatarstatus        int    `json:"avatarstatus"`
			AvatarCoverStatus   int    `json:"avatar_cover_status"`
			Regdate             int    `json:"regdate"`
			Logintime           int    `json:"logintime"`
			VerifyTitle         string `json:"verify_title"`
			VerifyStatus        int    `json:"verify_status"`
			UserType            int    `json:"user_type"`
			VerifyShowType      int    `json:"verify_show_type"`
			AvatarPluginStatus  int    `json:"avatar_plugin_status"`
			FetchType           string `json:"fetchType"`
			EntityType          string `json:"entityType"`
			EntityId            int    `json:"entityId"`
			DisplayUsername     string `json:"displayUsername"`
			Url                 string `json:"url"`
			UserAvatar          string `json:"userAvatar"`
			UserSmallAvatar     string `json:"userSmallAvatar"`
			UserBigAvatar       string `json:"userBigAvatar"`
			Cover               string `json:"cover"`
			VerifyIcon          string `json:"verify_icon"`
			VerifyLabel         string `json:"verify_label"`
			IsDeveloper         int    `json:"isDeveloper"`
			NextLevelExperience int    `json:"next_level_experience"`
			NextLevelPercentage string `json:"next_level_percentage"`
			LevelTodayMessage   string `json:"level_today_message"`
			LevelDetailUrl      string `json:"level_detail_url"`
			AvatarPluginUrl     string `json:"avatar_plugin_url"`
			FeedPluginUrl       string `json:"feed_plugin_url"`
			FeedPluginOpenUrl   string `json:"feed_plugin_open_url"`
		} `json:"userInfo"`
		RelationRows []struct {
			Id         int    `json:"id"`
			Logo       string `json:"logo"`
			Title      string `json:"title"`
			Url        string `json:"url"`
			EntityType string `json:"entityType"`
		} `json:"relationRows"`
		TargetRow struct {
			Id               int     `json:"id"`
			Logo             string  `json:"logo"`
			Title            string  `json:"title"`
			Url              string  `json:"url"`
			SubTitle         string  `json:"subTitle"`
			EntityType       string  `json:"entityType"`
			StarTotalCount   int     `json:"star_total_count"`
			StarAverageScore float64 `json:"star_average_score"`
		} `json:"targetRow"`
		UserAction struct {
			Like         int `json:"like"`
			Favorite     int `json:"favorite"`
			Follow       int `json:"follow"`
			Collect      int `json:"collect"`
			FollowAuthor int `json:"followAuthor"`
		} `json:"userAction"`
		HotReplyRows []struct {
			Id              int    `json:"id"`
			Ftype           int    `json:"ftype"`
			Fid             int    `json:"fid"`
			Rid             int    `json:"rid"`
			Rrid            int    `json:"rrid"`
			Uid             int    `json:"uid"`
			Username        string `json:"username"`
			Ruid            int    `json:"ruid"`
			Rusername       string `json:"rusername"`
			Pic             string `json:"pic"`
			Message         string `json:"message"`
			Replynum        int    `json:"replynum"`
			Likenum         int    `json:"likenum"`
			Burynum         int    `json:"burynum"`
			Reportnum       int    `json:"reportnum"`
			RankScore       int    `json:"rank_score"`
			Dateline        int    `json:"dateline"`
			Lastupdate      int    `json:"lastupdate"`
			IsFolded        int    `json:"is_folded"`
			Status          int    `json:"status"`
			MessageStatus   int    `json:"message_status"`
			BlockStatus     int    `json:"block_status"`
			RecentReplyIds  string `json:"recent_reply_ids"`
			FeedUid         int    `json:"feedUid"`
			FetchType       string `json:"fetchType"`
			EntityId        int    `json:"entityId"`
			AvatarFetchType string `json:"avatarFetchType"`
			UserAvatar      string `json:"userAvatar"`
			EntityTemplate  string `json:"entityTemplate"`
			EntityType      string `json:"entityType"`
			InfoHtml        string `json:"infoHtml"`
			IsFeedAuthor    int    `json:"isFeedAuthor"`
			UserInfo        struct {
				Uid                 int    `json:"uid"`
				Username            string `json:"username"`
				Admintype           int    `json:"admintype"`
				Groupid             int    `json:"groupid"`
				Usergroupid         int    `json:"usergroupid"`
				Level               int    `json:"level"`
				Experience          int    `json:"experience"`
				Status              int    `json:"status"`
				BlockStatus         int    `json:"block_status"`
				Usernamestatus      int    `json:"usernamestatus"`
				Avatarstatus        int    `json:"avatarstatus"`
				AvatarCoverStatus   int    `json:"avatar_cover_status"`
				Regdate             int    `json:"regdate"`
				Logintime           int    `json:"logintime"`
				VerifyTitle         string `json:"verify_title"`
				VerifyStatus        int    `json:"verify_status"`
				UserType            int    `json:"user_type"`
				VerifyShowType      int    `json:"verify_show_type"`
				AvatarPluginStatus  int    `json:"avatar_plugin_status"`
				FetchType           string `json:"fetchType"`
				EntityType          string `json:"entityType"`
				EntityId            int    `json:"entityId"`
				DisplayUsername     string `json:"displayUsername"`
				Url                 string `json:"url"`
				UserAvatar          string `json:"userAvatar"`
				UserSmallAvatar     string `json:"userSmallAvatar"`
				UserBigAvatar       string `json:"userBigAvatar"`
				Cover               string `json:"cover"`
				VerifyIcon          string `json:"verify_icon"`
				VerifyLabel         string `json:"verify_label"`
				IsDeveloper         int    `json:"isDeveloper"`
				NextLevelExperience int    `json:"next_level_experience"`
				NextLevelPercentage string `json:"next_level_percentage"`
				LevelTodayMessage   string `json:"level_today_message"`
				LevelDetailUrl      string `json:"level_detail_url"`
				AvatarPluginUrl     string `json:"avatar_plugin_url"`
				FeedPluginUrl       string `json:"feed_plugin_url"`
				FeedPluginOpenUrl   string `json:"feed_plugin_open_url"`
			} `json:"userInfo"`
			ReplyRows []struct {
				Id              int    `json:"id"`
				Ftype           int    `json:"ftype"`
				Fid             int    `json:"fid"`
				Rid             int    `json:"rid"`
				Rrid            int    `json:"rrid"`
				Uid             int    `json:"uid"`
				Username        string `json:"username"`
				Ruid            int    `json:"ruid"`
				Rusername       string `json:"rusername"`
				Pic             string `json:"pic"`
				Message         string `json:"message"`
				Replynum        int    `json:"replynum"`
				Likenum         int    `json:"likenum"`
				Burynum         int    `json:"burynum"`
				Reportnum       int    `json:"reportnum"`
				RankScore       int    `json:"rank_score"`
				Dateline        int    `json:"dateline"`
				Lastupdate      int    `json:"lastupdate"`
				IsFolded        int    `json:"is_folded"`
				Status          int    `json:"status"`
				MessageStatus   int    `json:"message_status"`
				BlockStatus     int    `json:"block_status"`
				RecentReplyIds  string `json:"recent_reply_ids"`
				FeedUid         int    `json:"feedUid"`
				FetchType       string `json:"fetchType"`
				EntityId        int    `json:"entityId"`
				AvatarFetchType string `json:"avatarFetchType"`
				UserAvatar      string `json:"userAvatar"`
				EntityTemplate  string `json:"entityTemplate"`
				EntityType      string `json:"entityType"`
				InfoHtml        string `json:"infoHtml"`
				IsFeedAuthor    int    `json:"isFeedAuthor"`
				UserInfo        struct {
					Uid                 int    `json:"uid"`
					Username            string `json:"username"`
					Admintype           int    `json:"admintype"`
					Groupid             int    `json:"groupid"`
					Usergroupid         int    `json:"usergroupid"`
					Level               int    `json:"level"`
					Experience          int    `json:"experience"`
					Status              int    `json:"status"`
					BlockStatus         int    `json:"block_status"`
					Usernamestatus      int    `json:"usernamestatus"`
					Avatarstatus        int    `json:"avatarstatus"`
					AvatarCoverStatus   int    `json:"avatar_cover_status"`
					Regdate             int    `json:"regdate"`
					Logintime           int    `json:"logintime"`
					VerifyTitle         string `json:"verify_title"`
					VerifyStatus        int    `json:"verify_status"`
					UserType            int    `json:"user_type"`
					VerifyShowType      int    `json:"verify_show_type"`
					AvatarPluginStatus  int    `json:"avatar_plugin_status"`
					FetchType           string `json:"fetchType"`
					EntityType          string `json:"entityType"`
					EntityId            int    `json:"entityId"`
					DisplayUsername     string `json:"displayUsername"`
					Url                 string `json:"url"`
					UserAvatar          string `json:"userAvatar"`
					UserSmallAvatar     string `json:"userSmallAvatar"`
					UserBigAvatar       string `json:"userBigAvatar"`
					Cover               string `json:"cover"`
					VerifyIcon          string `json:"verify_icon"`
					VerifyLabel         string `json:"verify_label"`
					IsDeveloper         int    `json:"isDeveloper"`
					NextLevelExperience int    `json:"next_level_experience"`
					NextLevelPercentage string `json:"next_level_percentage"`
					LevelTodayMessage   string `json:"level_today_message"`
					LevelDetailUrl      string `json:"level_detail_url"`
					AvatarPluginUrl     string `json:"avatar_plugin_url"`
					FeedPluginUrl       string `json:"feed_plugin_url"`
					FeedPluginOpenUrl   string `json:"feed_plugin_open_url"`
				} `json:"userInfo"`
			} `json:"replyRows"`
			ReplyRowsCount int `json:"replyRowsCount"`
			ReplyRowsMore  int `json:"replyRowsMore"`
		} `json:"hotReplyRows"`
		TopReplyRows []struct {
			Id              int      `json:"id"`
			Ftype           int      `json:"ftype"`
			Fid             int      `json:"fid"`
			Rid             int      `json:"rid"`
			Rrid            int      `json:"rrid"`
			Uid             int      `json:"uid"`
			Username        string   `json:"username"`
			Ruid            int      `json:"ruid"`
			Rusername       string   `json:"rusername"`
			Pic             string   `json:"pic"`
			Message         string   `json:"message"`
			Replynum        int      `json:"replynum"`
			Likenum         int      `json:"likenum"`
			Burynum         int      `json:"burynum"`
			Reportnum       int      `json:"reportnum"`
			RankScore       int      `json:"rank_score"`
			Dateline        int      `json:"dateline"`
			Lastupdate      int      `json:"lastupdate"`
			IsFolded        int      `json:"is_folded"`
			Status          int      `json:"status"`
			MessageStatus   int      `json:"message_status"`
			BlockStatus     int      `json:"block_status"`
			RecentReplyIds  string   `json:"recent_reply_ids"`
			FeedUid         int      `json:"feedUid"`
			FetchType       string   `json:"fetchType"`
			EntityId        int      `json:"entityId"`
			AvatarFetchType string   `json:"avatarFetchType"`
			UserAvatar      string   `json:"userAvatar"`
			EntityTemplate  string   `json:"entityTemplate"`
			EntityType      string   `json:"entityType"`
			InfoHtml        string   `json:"infoHtml"`
			IsFeedAuthor    int      `json:"isFeedAuthor"`
			PicArr          []string `json:"picArr"`
			UserInfo        struct {
				Uid                 int    `json:"uid"`
				Username            string `json:"username"`
				Admintype           int    `json:"admintype"`
				Groupid             int    `json:"groupid"`
				Usergroupid         int    `json:"usergroupid"`
				Level               int    `json:"level"`
				Experience          int    `json:"experience"`
				Status              int    `json:"status"`
				BlockStatus         int    `json:"block_status"`
				Usernamestatus      int    `json:"usernamestatus"`
				Avatarstatus        int    `json:"avatarstatus"`
				AvatarCoverStatus   int    `json:"avatar_cover_status"`
				Regdate             int    `json:"regdate"`
				Logintime           int    `json:"logintime"`
				VerifyTitle         string `json:"verify_title"`
				VerifyStatus        int    `json:"verify_status"`
				UserType            int    `json:"user_type"`
				VerifyShowType      int    `json:"verify_show_type"`
				AvatarPluginStatus  int    `json:"avatar_plugin_status"`
				FetchType           string `json:"fetchType"`
				EntityType          string `json:"entityType"`
				EntityId            int    `json:"entityId"`
				DisplayUsername     string `json:"displayUsername"`
				Url                 string `json:"url"`
				UserAvatar          string `json:"userAvatar"`
				UserSmallAvatar     string `json:"userSmallAvatar"`
				UserBigAvatar       string `json:"userBigAvatar"`
				Cover               string `json:"cover"`
				VerifyIcon          string `json:"verify_icon"`
				VerifyLabel         string `json:"verify_label"`
				IsDeveloper         int    `json:"isDeveloper"`
				NextLevelExperience int    `json:"next_level_experience"`
				NextLevelPercentage string `json:"next_level_percentage"`
				LevelTodayMessage   string `json:"level_today_message"`
				LevelDetailUrl      string `json:"level_detail_url"`
				AvatarPluginUrl     string `json:"avatar_plugin_url"`
				FeedPluginUrl       string `json:"feed_plugin_url"`
				FeedPluginOpenUrl   string `json:"feed_plugin_open_url"`
			} `json:"userInfo"`
			ReplyRows []struct {
				Id              int    `json:"id"`
				Ftype           int    `json:"ftype"`
				Fid             int    `json:"fid"`
				Rid             int    `json:"rid"`
				Rrid            int    `json:"rrid"`
				Uid             int    `json:"uid"`
				Username        string `json:"username"`
				Ruid            int    `json:"ruid"`
				Rusername       string `json:"rusername"`
				Pic             string `json:"pic"`
				Message         string `json:"message"`
				Replynum        int    `json:"replynum"`
				Likenum         int    `json:"likenum"`
				Burynum         int    `json:"burynum"`
				Reportnum       int    `json:"reportnum"`
				RankScore       int    `json:"rank_score"`
				Dateline        int    `json:"dateline"`
				Lastupdate      int    `json:"lastupdate"`
				IsFolded        int    `json:"is_folded"`
				Status          int    `json:"status"`
				MessageStatus   int    `json:"message_status"`
				BlockStatus     int    `json:"block_status"`
				RecentReplyIds  string `json:"recent_reply_ids"`
				FeedUid         int    `json:"feedUid"`
				FetchType       string `json:"fetchType"`
				EntityId        int    `json:"entityId"`
				AvatarFetchType string `json:"avatarFetchType"`
				UserAvatar      string `json:"userAvatar"`
				EntityTemplate  string `json:"entityTemplate"`
				EntityType      string `json:"entityType"`
				InfoHtml        string `json:"infoHtml"`
				IsFeedAuthor    int    `json:"isFeedAuthor"`
				UserInfo        struct {
					Uid                 int    `json:"uid"`
					Username            string `json:"username"`
					Admintype           int    `json:"admintype"`
					Groupid             int    `json:"groupid"`
					Usergroupid         int    `json:"usergroupid"`
					Level               int    `json:"level"`
					Experience          int    `json:"experience"`
					Status              int    `json:"status"`
					BlockStatus         int    `json:"block_status"`
					Usernamestatus      int    `json:"usernamestatus"`
					Avatarstatus        int    `json:"avatarstatus"`
					AvatarCoverStatus   int    `json:"avatar_cover_status"`
					Regdate             int    `json:"regdate"`
					Logintime           int    `json:"logintime"`
					VerifyTitle         string `json:"verify_title"`
					VerifyStatus        int    `json:"verify_status"`
					UserType            int    `json:"user_type"`
					VerifyShowType      int    `json:"verify_show_type"`
					AvatarPluginStatus  int    `json:"avatar_plugin_status"`
					FetchType           string `json:"fetchType"`
					EntityType          string `json:"entityType"`
					EntityId            int    `json:"entityId"`
					DisplayUsername     string `json:"displayUsername"`
					Url                 string `json:"url"`
					UserAvatar          string `json:"userAvatar"`
					UserSmallAvatar     string `json:"userSmallAvatar"`
					UserBigAvatar       string `json:"userBigAvatar"`
					Cover               string `json:"cover"`
					VerifyIcon          string `json:"verify_icon"`
					VerifyLabel         string `json:"verify_label"`
					IsDeveloper         int    `json:"isDeveloper"`
					NextLevelExperience int    `json:"next_level_experience"`
					NextLevelPercentage string `json:"next_level_percentage"`
					LevelTodayMessage   string `json:"level_today_message"`
					LevelDetailUrl      string `json:"level_detail_url"`
					AvatarPluginUrl     string `json:"avatar_plugin_url"`
					FeedPluginUrl       string `json:"feed_plugin_url"`
					FeedPluginOpenUrl   string `json:"feed_plugin_open_url"`
				} `json:"userInfo"`
			} `json:"replyRows"`
			ReplyRowsCount int `json:"replyRowsCount"`
			ReplyRowsMore  int `json:"replyRowsMore"`
		} `json:"topReplyRows"`
		DetailSponsorCard struct {
			EntityType     string `json:"entityType"`
			EntityTemplate string `json:"entityTemplate"`
			Title          string `json:"title"`
			Url            string `json:"url"`
			Entities       []struct {
				GoodsBuyText    string  `json:"goods_buy_text"`
				GoodsBuyUrl     string  `json:"goods_buy_url"`
				GoodsPic        string  `json:"goods_pic"`
				GoodsPromoPrice string  `json:"goods_promo_price"`
				GoodsPromoTitle string  `json:"goods_promo_title"`
				GoodsTags       string  `json:"goods_tags"`
				GoodsTitle      string  `json:"goods_title"`
				GoodsUrl        string  `json:"goods_url"`
				GoodsIsDirect   string  `json:"goods_is_direct"`
				Id              string  `json:"id"`
				GoodsMallId     string  `json:"goods_mall_id"`
				GoodsCatId      string  `json:"goods_cat_id"`
				IndexName       string  `json:"index_name"`
				QueryTotal      int     `json:"_queryTotal"`
				QueryViewTotal  int     `json:"_queryViewTotal"`
				QuerySearchTime float64 `json:"_querySearchTime"`
				Title           string  `json:"title"`
				EntityId        string  `json:"entityId"`
				MallInfo        struct {
					Id         int    `json:"id"`
					Name       string `json:"name"`
					MallTitle  string `json:"mall_title"`
					MallDomain string `json:"mall_domain"`
					MallLogo   string `json:"mall_logo"`
					GoodsCount int    `json:"goods_count"`
					Sort       int    `json:"sort"`
				} `json:"mallInfo"`
				CategoryInfo struct {
					CatId      int    `json:"cat_id"`
					CatTitle   string `json:"cat_title"`
					CatTags    string `json:"cat_tags"`
					GoodsCount int    `json:"goods_count"`
				} `json:"categoryInfo"`
				EntityType string `json:"entityType"`
			} `json:"entities"`
			EntityId     int    `json:"entityId"`
			EntityFixed  int    `json:"entityFixed"`
			Pic          string `json:"pic"`
			Lastupdate   int    `json:"lastupdate"`
			ExtraDataArr struct {
				CardDividerTop           int    `json:"cardDividerTop"`
				CardDividerBottom        int    `json:"cardDividerBottom"`
				CardContainerPaddingTop  string `json:"cardContainerPaddingTop"`
				CardContainerRadius      string `json:"cardContainerRadius"`
				CardStat                 string `json:"cardStat"`
				ScrollToCommentTop       string `json:"scrollToCommentTop"`
				ScrollToCommentTopOffset string `json:"scrollToCommentTopOffset"`
				CardStatName             string `json:"cardStatName"`
			} `json:"extraDataArr"`
			ExtraData string `json:"extraData"`
		} `json:"detailSponsorCard"`
	} `json:"data"`
}
