export const styles = {
    carouselContainer: {
        position: 'relative',
        margin: '20px 0',
    },
    carousel: {
        display: 'flex',
        overflowX: 'scroll',
        scrollSnapType: 'x mandatory',
        gap: '10px',
        padding: '10px 0',
        scrollbarWidth: 'none',
        msOverflowStyle: 'none',
    },
    carouselImageContainer: {
        width: '100%',
        flexShrink: 0,
        scrollSnapAlign: 'center',
        aspectRatio: '3/4',
        maxHeight: '600px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: '4px',
        overflow: 'hidden',
        position: 'relative',
        backgroundColor: 'transparent',
    },
    carouselImage: {
        maxWidth: '100%',
        maxHeight: '100%',
        width: 'auto',
        height: 'auto',
        objectFit: 'contain',
        borderRadius: '4px',
        cursor: 'pointer',
        margin: '0 auto',
        display: 'block',
        boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
    },
    carouselButton: {
        position: 'absolute',
        top: '50%',
        transform: 'translateY(-50%)',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        color: 'white',
        border: 'none',
        borderRadius: '50%',
        width: '40px',
        height: '40px',
        fontSize: '20px',
        cursor: 'pointer',
        zIndex: 1,
    },
    container: {
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '20px',
        color: '#333',
        backgroundColor: 'transparent',
        paddingBottom: '100px',
    },
    centered: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: 'calc(100vh - 200px)',
        fontSize: '1.2em',
    },
    header: {
        borderBottom: '1px solid #eee',
        paddingBottom: '20px',
        marginBottom: '20px',
    },
    title: {
        fontSize: '1.5em',
        fontWeight: 'bold',
        marginBottom: '10px',
    },
    userInfo: {
        display: 'flex',
        alignItems: 'center',
        position: 'relative',
        gap: '10px',
        minHeight: '50px',
        flexWrap: 'wrap',
    },
    avatar: {
        width: '50px',
        height: '50px',
        borderRadius: '50%',
        marginRight: '15px',
        flexShrink: 0,
    },
    username: {
        fontWeight: 'bold',
    },
    dateline: {
        fontSize: '0.9em',
        color: '#888',
    },
    content: {
        lineHeight: '1.8',
        fontSize: '1.1em',
        maxWidth: '100%',
        overflowWrap: 'break-word',
        wordWrap: 'break-word',
        wordBreak: 'break-word',
    },
    textBlock: {
        marginBottom: '20px',
        wordWrap: 'break-word',
        maxWidth: '100%',
        overflowWrap: 'break-word',
        wordBreak: 'break-word',
    },
    imageContainer: {
        margin: '20px 0',
        textAlign: 'center',
        display: 'block',
    },
    image: {
        maxWidth: '100%',
        borderRadius: '4px',
        boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
        display: 'block',
        margin: '0 auto',
    },
    imageDescription: {
        marginTop: '8px',
        color: '#666',
        fontSize: '0.9em',
        textAlign: 'center',
        display: 'block',
    },
    floatingBarContainer: {
        position: 'fixed',
        bottom: '20px',
        left: '0',
        right: '0',
        display: 'flex',
        justifyContent: 'center',
        zIndex: 1000,
    },
    floatingBar: {
        height: '50px',
        backgroundColor: '#28a745',
        borderRadius: '25px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 40px 0 20px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
        position: 'relative',
    },
    originalLinkButton: {
        color: 'white',
        textDecoration: 'none',
        fontWeight: 'bold',
        fontSize: '16px',
        lineHeight: '50px',
    },
    closeButton: {
        position: 'absolute',
        top: '50%',
        right: '15px',
        transform: 'translateY(-50%)',
        background: 'rgba(0,0,0,0.2)',
        color: 'white',
        border: 'none',
        borderRadius: '50%',
        width: '20px',
        height: '20px',
        fontSize: '14px',
        lineHeight: '20px',
        textAlign: 'center',
        cursor: 'pointer',
    },
    lightbox: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2000,
        cursor: 'pointer',
        overflow: 'hidden',
    },
    lightboxSliderContainer: {
        display: 'flex',
        width: '100%',
        height: '100%',
        position: 'absolute',
        top: 0,
        left: 0,
        willChange: 'transform',
    },
    lightboxSlide: {
        minWidth: '100%',
        height: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        flexShrink: 0,
    },
    lightboxImage: {
        maxWidth: '95vw',
        maxHeight: '100vh',
        width: 'auto',
        height: 'auto',
        objectFit: 'contain',
        boxShadow: '0 0 25px rgba(0,0,0,0.5)',
        userSelect: 'none',
    },
    controlsContainer: {
        display: 'flex',
        alignItems: 'center',
        marginLeft: 'auto',
        flexShrink: 0,
        width: '85px',
        justifyContent: 'flex-end',
        order: 999,
    },
    switchLabel: {
        fontSize: '0.85em',
        marginRight: '8px',
        color: '#666',
    },
    imageGridContainer: {
        margin: '20px 0',
        width: '100%',
    },
    imageGrid: {
        display: 'grid',
        gap: '8px',
        width: '100%',
        maxWidth: '100%',
        justifyContent: 'center',
        alignContent: 'center',
    },
    imageGridItem: {
        position: 'relative',
        aspectRatio: '1',
        borderRadius: '4px',
        overflow: 'hidden',
        backgroundColor: '#f5f5f5',
    },
    gridImage: {
        width: '100%',
        height: '100%',
        objectFit: 'cover',
        borderRadius: '4px',
        cursor: 'pointer',
        transition: 'opacity 0.2s ease',
        boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    },
    imageCountIndicator: {
        textAlign: 'center',
        padding: '15px',
        color: '#666',
        fontSize: '0.9em',
        backgroundColor: '#f9f9f9',
        borderRadius: '4px',
        marginTop: '10px',
        border: '1px solid #e0e0e0',
    },
    lightboxCloseButton: {
        position: 'absolute',
        top: '20px',
        right: '20px',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        color: 'white',
        border: 'none',
        borderRadius: '50%',
        width: '40px',
        height: '40px',
        fontSize: '24px',
        cursor: 'pointer',
        zIndex: 2001,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    lightboxNavButton: {
        position: 'absolute',
        top: '50%',
        transform: 'translateY(-50%)',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        color: 'white',
        border: 'none',
        borderRadius: '50%',
        width: '50px',
        height: '50px',
        fontSize: '24px',
        cursor: 'pointer',
        zIndex: 2001,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transition: 'background-color 0.3s ease',
    },
    lightboxIndicator: {
        position: 'absolute',
        bottom: '20px',
        left: '50%',
        transform: 'translateX(-50%)',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        color: 'white',
        padding: '8px 16px',
        borderRadius: '20px',
        fontSize: '14px',
        zIndex: 2001,
    },
    imagePlaceholder: {
        width: '100%',
        height: '100%',
        backgroundColor: '#f0f0f0',
        borderRadius: '4px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        border: 'none',
    },
    placeholderLoader: {
        width: '24px',
        height: '24px',
        borderRadius: '50%',
        border: '2px solid #e9ecef',
        borderTop: '2px solid #28a745',
        animation: 'spin 1s linear infinite',
    },
    placeholderDot: {
        display: 'none', // 隐藏，因为我们使用边框动画
    },
    // Product Album Card styles
    goodsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
        margin: '20px 0',
    },
    goodsLevelGroup: {
        borderRadius: '8px',
        overflow: 'hidden',
        border: '2px solid',
        backgroundColor: 'transparent',
        display: 'flex',
        position: 'relative',
    },
    goodsRankBadge: {
        flexShrink: 0,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        writingMode: 'vertical-rl',
        textOrientation: 'upright',
        padding: '16px 0',
    },
    goodsItemsContainer: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
    },
    goodsCard: {
        position: 'relative',
        backgroundColor: 'transparent',
        display: 'flex',
        padding: '16px',
        gap: '16px',
    },
    goodsCardContent: {
        flex: 1,
        display: 'flex',
        gap: '16px',
    },
    goodsThumbnailContainer: {
        flexShrink: 0,
        borderRadius: '8px',
        overflow: 'hidden',
        backgroundColor: '#f5f5f5',
        border: '1px solid #e0e0e0',
    },
    goodsThumbnail: {
        width: '100%',
        height: '100%',
        objectFit: 'contain',
    },
    goodsInfo: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    goodsTitle: {
        fontSize: '16px',
        fontWeight: 'bold',
        margin: 0,
        lineHeight: '1.4',
        color: 'inherit',
    },
    goodsSpecs: {
        fontSize: '13px',
        lineHeight: '1.6',
        color: '#666',
        flex: 1,
        overflow: 'hidden',
        whiteSpace: 'pre-wrap',
    },
    goodsMeta: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
        marginTop: 'auto',
    },
    goodsPriceContainer: {
        display: 'flex',
        alignItems: 'baseline',
        gap: '8px',
    },
    goodsPrice: {
        fontSize: '18px',
        fontWeight: 'bold',
        color: '#ff6b35',
    },
    goodsOriginalPrice: {
        fontSize: '14px',
        color: '#888',
        textDecoration: 'line-through',
    },
    goodsShopInfo: {
        fontSize: '12px',
        color: '#999',
    },
    goodsButton: {
        display: 'inline-block',
        padding: '6px 16px',
        backgroundColor: '#4ECDC4',
        color: '#000',
        textDecoration: 'none',
        borderRadius: '4px',
        fontSize: '13px',
        fontWeight: 'bold',
        textAlign: 'center',
        alignSelf: 'flex-start',
        marginTop: '8px',
        transition: 'background-color 0.2s',
    },
    goodsImagePreview: {
        display: 'flex',
        gap: '8px',
        marginTop: '8px',
        flexWrap: 'wrap',
    },
    goodsPreviewImage: {
        width: '60px',
        height: '60px',
        objectFit: 'cover',
        borderRadius: '4px',
        border: '1px solid #ddd',
    },
};