export const styles = {
    carouselContainer: {
        position: 'relative',
        margin: '20px 0',
    },
    carousel: {
        display: 'flex',
        overflowX: 'scroll',
        scrollSnapType: 'x mandatory',
        gap: '10px',
        padding: '10px 0',
        scrollbarWidth: 'none',
        msOverflowStyle: 'none',
    },
    carouselImageContainer: {
        width: '100%',
        flexShrink: 0,
        scrollSnapAlign: 'center',
        aspectRatio: '3/4',
        maxHeight: '600px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: '8px',
        overflow: 'hidden',
        position: 'relative',
        backgroundColor: 'transparent',
    },
    carouselImage: {
        maxWidth: '100%',
        maxHeight: '100%',
        width: 'auto',
        height: 'auto',
        objectFit: 'contain',
        borderRadius: '8px',
        cursor: 'pointer',
        margin: '0 auto',
        display: 'block',
        boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
    },
    carouselButton: {
        position: 'absolute',
        top: '50%',
        transform: 'translateY(-50%)',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        color: 'white',
        border: 'none',
        borderRadius: '50%',
        width: '40px',
        height: '40px',
        fontSize: '20px',
        cursor: 'pointer',
        zIndex: 1,
    },
    container: {
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '20px',
        color: '#333',
        backgroundColor: 'transparent',
        paddingBottom: '100px',
    },
    centered: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: 'calc(100vh - 200px)',
        fontSize: '1.2em',
    },
    header: {
        borderBottom: '1px solid #eee',
        paddingBottom: '20px',
        marginBottom: '20px',
    },
    title: {
        fontSize: '1.8em',
        fontWeight: 'bold',
        marginBottom: '10px',
    },
    userInfo: {
        display: 'flex',
        alignItems: 'center',
        position: 'relative',
    },
    avatar: {
        width: '50px',
        height: '50px',
        borderRadius: '50%',
        marginRight: '15px',
    },
    username: {
        fontWeight: 'bold',
    },
    dateline: {
        fontSize: '0.9em',
        color: '#888',
    },
    content: {
        lineHeight: '1.8',
        fontSize: '1.1em',
    },
    textBlock: {
        marginBottom: '20px',
        wordWrap: 'break-word',
    },
    imageContainer: {
        margin: '20px 0',
        textAlign: 'center',
    },
    image: {
        maxWidth: '100%',
        borderRadius: '8px',
        boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
    },
    imageDescription: {
        marginTop: '8px',
        color: '#666',
        fontSize: '0.9em',
    },
    floatingBarContainer: {
        position: 'fixed',
        bottom: '20px',
        left: '0',
        right: '0',
        display: 'flex',
        justifyContent: 'center',
        zIndex: 1000,
    },
    floatingBar: {
        height: '50px',
        backgroundColor: '#28a745',
        borderRadius: '25px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 40px 0 20px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
        position: 'relative',
    },
    originalLinkButton: {
        color: 'white',
        textDecoration: 'none',
        fontWeight: 'bold',
        fontSize: '16px',
        lineHeight: '50px',
    },
    closeButton: {
        position: 'absolute',
        top: '50%',
        right: '15px',
        transform: 'translateY(-50%)',
        background: 'rgba(0,0,0,0.2)',
        color: 'white',
        border: 'none',
        borderRadius: '50%',
        width: '20px',
        height: '20px',
        fontSize: '14px',
        lineHeight: '20px',
        textAlign: 'center',
        cursor: 'pointer',
    },
    lightbox: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2000,
        cursor: 'pointer',
    },
    lightboxImage: {
        maxWidth: '90%',
        maxHeight: '90%',
        boxShadow: '0 0 25px rgba(0,0,0,0.5)',
    },
    controlsContainer: {
        display: 'flex',
        alignItems: 'center',
        position: 'absolute',
        right: 0,
    },
    switchLabel: {
        fontSize: '1em',
        marginRight: '10px',
    },
    telegramContainer: {
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
        maxWidth: '680px',
        margin: '0 auto',
        padding: '0',
        backgroundColor: '#fff',
        color: '#222',
        lineHeight: '1.6',
    },
    telegramPageHeader: {
        display: 'none',
    },
    telegramCoverSection: {
        margin: '0',
        padding: '0',
        width: '100%',
    },
    telegramCoverFigure: {
        margin: '0',
        padding: '0',
        width: '100%',
    },
    telegramCoverImage: {
        width: '100%',
        height: 'auto',
        display: 'block',
    },
    telegramTitle: {
        fontSize: '2em',
        fontWeight: 'bold',
        margin: '30px 20px 15px',
        lineHeight: '1.3',
        color: '#000',
    },
    telegramContentSection: {
        fontSize: '1.05em',
        lineHeight: '1.7',
        padding: '0 20px',
        marginBottom: '30px',
    },
    telegramSourceLink: {
        margin: '0',
        fontSize: '0.95em',
    },
    telegramFooter: {
        padding: '20px',
        borderTop: '1px solid #e5e5e5',
        textAlign: 'center',
        color: '#999',
        fontSize: '0.9em',
    },
    telegramLink: {
        color: '#2481cc',
        textDecoration: 'none',
        fontSize: '0.9em',
        fontWeight: '500',
    },
};